apiVersion: v1
kind: Service
metadata:
  name: generatorapi
  labels:
    name: generatorapi
spec:
  type: "{{.Values.service.type}}"
  ports:
  - name: http
    port: {{.Values.service.port}}
    targetPort: {{.Values.service.port}}
  selector:
    app: generatorapi